-- =============================================================================
-- bsale_raw — verificación post-DDL (SÓLO LECTURA de pg_catalog)
--
-- Ejecutar después de 001..008 y ANTES de 009_seed_sources.sql (no depende del seed ni de
-- ninguna fila). No crea, no modifica, no borra nada. Compara el catálogo real con lo esperado:
--   tablas, columnas (tipo + nulabilidad), constraints (PK/FK/UNIQUE/CHECK por nombre),
--   columnas de cada PK, destino de cada FK, índices (nombre + unicidad).
-- Cualquier faltante o sobrante → RAISE EXCEPTION con el detalle (drift).
--
-- El bloque GENERATED se deriva de las migraciones (backend/tests/bsale_raw/_raw_sql_schema.py);
-- el test test_verify_block_matches_migrations falla si queda desalineado.
-- =============================================================================

DO $verify$
DECLARE
    -- BEGIN GENERATED EXPECTED
    expected_tables text[] := ARRAY[
        'clients',
        'document_change_log',
        'document_details',
        'document_references',
        'document_sellers',
        'document_types',
        'documents',
        'offices',
        'price_lists',
        'product_taxes',
        'product_types',
        'products',
        'sources',
        'stock_consumption_details',
        'stock_consumptions',
        'stock_reception_details',
        'stock_receptions',
        'stocks',
        'sync_cursors',
        'sync_entity_runs',
        'sync_runs',
        'sync_state',
        'taxes',
        'variant_costs',
        'variant_prices',
        'variants',
        'webhook_events',
        'webhook_resource_responses'
    ];
    expected_columns text[] := ARRAY[
        'clients.api_fetched_at:timestamp with time zone:NOT NULL',
        'clients.bsale_id:bigint:NOT NULL',
        'clients.code:text:NULL',
        'clients.company_id:bigint:NOT NULL',
        'clients.company_name:text:NULL',
        'clients.email:text:NULL',
        'clients.first_name:text:NULL',
        'clients.first_seen_at:timestamp with time zone:NOT NULL',
        'clients.last_changed_at:timestamp with time zone:NOT NULL',
        'clients.last_name:text:NULL',
        'clients.last_seen_at:timestamp with time zone:NOT NULL',
        'clients.last_source:text:NOT NULL',
        'clients.missing_since:timestamp with time zone:NULL',
        'clients.payload:jsonb:NOT NULL',
        'clients.payload_hash:text:NOT NULL',
        'clients.state:smallint:NULL',
        'clients.sync_run_id:bigint:NULL',
        'document_change_log.affected_variant_ids:bigint[]:NOT NULL',
        'document_change_log.api_fetched_at:timestamp with time zone:NOT NULL',
        'document_change_log.attributes_changed:boolean:NOT NULL',
        'document_change_log.change_kind:text:NOT NULL',
        'document_change_log.commercial_state:text:NULL',
        'document_change_log.company_id:bigint:NOT NULL',
        'document_change_log.current_variant_ids:bigint[]:NOT NULL',
        'document_change_log.details_changed:boolean:NOT NULL',
        'document_change_log.detected_at:timestamp with time zone:NOT NULL',
        'document_change_log.detected_by:text:NOT NULL',
        'document_change_log.document_id:bigint:NOT NULL',
        'document_change_log.document_type_id:bigint:NULL',
        'document_change_log.header_changed:boolean:NOT NULL',
        'document_change_log.id:bigint:NOT NULL',
        'document_change_log.payload_hash:text:NOT NULL',
        'document_change_log.previous_commercial_state:text:NULL',
        'document_change_log.previous_payload_hash:text:NULL',
        'document_change_log.previous_state:smallint:NULL',
        'document_change_log.previous_variant_ids:bigint[]:NOT NULL',
        'document_change_log.previous_version_hash:text:NULL',
        'document_change_log.references_changed:boolean:NOT NULL',
        'document_change_log.sellers_changed:boolean:NOT NULL',
        'document_change_log.state:smallint:NULL',
        'document_change_log.stock_refresh_done_at:timestamp with time zone:NULL',
        'document_change_log.stock_refresh_requested_at:timestamp with time zone:NULL',
        'document_change_log.sync_run_id:bigint:NULL',
        'document_change_log.version_hash:text:NOT NULL',
        'document_change_log.webhook_event_id:bigint:NULL',
        'document_details.api_fetched_at:timestamp with time zone:NOT NULL',
        'document_details.bsale_id:bigint:NOT NULL',
        'document_details.company_id:bigint:NOT NULL',
        'document_details.document_id:bigint:NOT NULL',
        'document_details.document_version_hash:text:NOT NULL',
        'document_details.first_seen_at:timestamp with time zone:NOT NULL',
        'document_details.last_changed_at:timestamp with time zone:NOT NULL',
        'document_details.last_seen_at:timestamp with time zone:NOT NULL',
        'document_details.last_source:text:NOT NULL',
        'document_details.line_number:integer:NULL',
        'document_details.payload:jsonb:NOT NULL',
        'document_details.payload_hash:text:NOT NULL',
        'document_details.quantity:numeric:NULL',
        'document_details.related_detail_id:bigint:NULL',
        'document_details.sync_run_id:bigint:NULL',
        'document_details.variant_id:bigint:NULL',
        'document_references.api_fetched_at:timestamp with time zone:NOT NULL',
        'document_references.bsale_id:bigint:NOT NULL',
        'document_references.company_id:bigint:NOT NULL',
        'document_references.document_id:bigint:NOT NULL',
        'document_references.document_version_hash:text:NOT NULL',
        'document_references.dte_code_id:bigint:NULL',
        'document_references.first_seen_at:timestamp with time zone:NOT NULL',
        'document_references.last_changed_at:timestamp with time zone:NOT NULL',
        'document_references.last_seen_at:timestamp with time zone:NOT NULL',
        'document_references.last_source:text:NOT NULL',
        'document_references.number:text:NULL',
        'document_references.payload:jsonb:NOT NULL',
        'document_references.payload_hash:text:NOT NULL',
        'document_references.reference_date:date:NULL',
        'document_references.sync_run_id:bigint:NULL',
        'document_sellers.api_fetched_at:timestamp with time zone:NOT NULL',
        'document_sellers.company_id:bigint:NOT NULL',
        'document_sellers.document_id:bigint:NOT NULL',
        'document_sellers.document_version_hash:text:NOT NULL',
        'document_sellers.first_seen_at:timestamp with time zone:NOT NULL',
        'document_sellers.last_changed_at:timestamp with time zone:NOT NULL',
        'document_sellers.last_seen_at:timestamp with time zone:NOT NULL',
        'document_sellers.last_source:text:NOT NULL',
        'document_sellers.payload:jsonb:NOT NULL',
        'document_sellers.payload_hash:text:NOT NULL',
        'document_sellers.sync_run_id:bigint:NULL',
        'document_sellers.user_id:bigint:NOT NULL',
        'document_types.api_fetched_at:timestamp with time zone:NOT NULL',
        'document_types.bsale_id:bigint:NOT NULL',
        'document_types.code_sii:text:NULL',
        'document_types.company_id:bigint:NOT NULL',
        'document_types.first_seen_at:timestamp with time zone:NOT NULL',
        'document_types.is_electronic:smallint:NULL',
        'document_types.last_changed_at:timestamp with time zone:NOT NULL',
        'document_types.last_seen_at:timestamp with time zone:NOT NULL',
        'document_types.last_source:text:NOT NULL',
        'document_types.missing_since:timestamp with time zone:NULL',
        'document_types.name:text:NULL',
        'document_types.payload:jsonb:NOT NULL',
        'document_types.payload_hash:text:NOT NULL',
        'document_types.state:smallint:NULL',
        'document_types.sync_run_id:bigint:NULL',
        'documents.api_fetched_at:timestamp with time zone:NOT NULL',
        'documents.attributes_payload:jsonb:NULL',
        'documents.bsale_id:bigint:NOT NULL',
        'documents.children_fetched_at:timestamp with time zone:NULL',
        'documents.children_hash:text:NULL',
        'documents.client_id:bigint:NULL',
        'documents.commercial_state:text:NULL',
        'documents.company_id:bigint:NOT NULL',
        'documents.details_complete:boolean:NOT NULL',
        'documents.details_count:integer:NULL',
        'documents.document_type_id:bigint:NULL',
        'documents.emission_date:date:NULL',
        'documents.first_seen_at:timestamp with time zone:NOT NULL',
        'documents.generation_date:timestamp with time zone:NULL',
        'documents.informed_sii:smallint:NULL',
        'documents.last_changed_at:timestamp with time zone:NOT NULL',
        'documents.last_seen_at:timestamp with time zone:NOT NULL',
        'documents.last_source:text:NOT NULL',
        'documents.missing_since:timestamp with time zone:NULL',
        'documents.number:bigint:NULL',
        'documents.office_id:bigint:NULL',
        'documents.payload:jsonb:NOT NULL',
        'documents.payload_hash:text:NOT NULL',
        'documents.state:smallint:NULL',
        'documents.sync_run_id:bigint:NULL',
        'documents.total_amount:numeric:NULL',
        'documents.user_id:bigint:NULL',
        'documents.version_changed_at:timestamp with time zone:NULL',
        'documents.version_hash:text:NULL',
        'documents.watch_closed_at:timestamp with time zone:NULL',
        'documents.watch_stable_reads:integer:NOT NULL',
        'documents.watch_terminal_seen_at:timestamp with time zone:NULL',
        'offices.api_fetched_at:timestamp with time zone:NOT NULL',
        'offices.bsale_id:bigint:NOT NULL',
        'offices.company_id:bigint:NOT NULL',
        'offices.cost_center:text:NULL',
        'offices.first_seen_at:timestamp with time zone:NOT NULL',
        'offices.is_virtual:smallint:NULL',
        'offices.last_changed_at:timestamp with time zone:NOT NULL',
        'offices.last_seen_at:timestamp with time zone:NOT NULL',
        'offices.last_source:text:NOT NULL',
        'offices.missing_since:timestamp with time zone:NULL',
        'offices.name:text:NULL',
        'offices.payload:jsonb:NOT NULL',
        'offices.payload_hash:text:NOT NULL',
        'offices.state:smallint:NULL',
        'offices.sync_run_id:bigint:NULL',
        'price_lists.api_fetched_at:timestamp with time zone:NOT NULL',
        'price_lists.bsale_id:bigint:NOT NULL',
        'price_lists.coin_id:bigint:NULL',
        'price_lists.company_id:bigint:NOT NULL',
        'price_lists.first_seen_at:timestamp with time zone:NOT NULL',
        'price_lists.last_changed_at:timestamp with time zone:NOT NULL',
        'price_lists.last_seen_at:timestamp with time zone:NOT NULL',
        'price_lists.last_source:text:NOT NULL',
        'price_lists.missing_since:timestamp with time zone:NULL',
        'price_lists.name:text:NULL',
        'price_lists.payload:jsonb:NOT NULL',
        'price_lists.payload_hash:text:NOT NULL',
        'price_lists.state:smallint:NULL',
        'price_lists.sync_run_id:bigint:NULL',
        'product_taxes.api_fetched_at:timestamp with time zone:NOT NULL',
        'product_taxes.company_id:bigint:NOT NULL',
        'product_taxes.first_seen_at:timestamp with time zone:NOT NULL',
        'product_taxes.items_count:integer:NOT NULL',
        'product_taxes.last_changed_at:timestamp with time zone:NOT NULL',
        'product_taxes.last_seen_at:timestamp with time zone:NOT NULL',
        'product_taxes.last_source:text:NOT NULL',
        'product_taxes.missing_since:timestamp with time zone:NULL',
        'product_taxes.payload:jsonb:NOT NULL',
        'product_taxes.payload_hash:text:NOT NULL',
        'product_taxes.product_id:bigint:NOT NULL',
        'product_taxes.sync_run_id:bigint:NULL',
        'product_taxes.tax_ids:bigint[]:NOT NULL',
        'product_types.api_fetched_at:timestamp with time zone:NOT NULL',
        'product_types.bsale_id:bigint:NOT NULL',
        'product_types.company_id:bigint:NOT NULL',
        'product_types.first_seen_at:timestamp with time zone:NOT NULL',
        'product_types.last_changed_at:timestamp with time zone:NOT NULL',
        'product_types.last_seen_at:timestamp with time zone:NOT NULL',
        'product_types.last_source:text:NOT NULL',
        'product_types.missing_since:timestamp with time zone:NULL',
        'product_types.name:text:NULL',
        'product_types.payload:jsonb:NOT NULL',
        'product_types.payload_hash:text:NOT NULL',
        'product_types.state:smallint:NULL',
        'product_types.sync_run_id:bigint:NULL',
        'products.api_fetched_at:timestamp with time zone:NOT NULL',
        'products.bsale_id:bigint:NOT NULL',
        'products.classification:smallint:NULL',
        'products.company_id:bigint:NOT NULL',
        'products.first_seen_at:timestamp with time zone:NOT NULL',
        'products.last_changed_at:timestamp with time zone:NOT NULL',
        'products.last_seen_at:timestamp with time zone:NOT NULL',
        'products.last_source:text:NOT NULL',
        'products.missing_since:timestamp with time zone:NULL',
        'products.name:text:NULL',
        'products.payload:jsonb:NOT NULL',
        'products.payload_hash:text:NOT NULL',
        'products.product_type_id:bigint:NULL',
        'products.state:smallint:NULL',
        'products.stock_control:smallint:NULL',
        'products.sync_run_id:bigint:NULL',
        'sources.active:boolean:NOT NULL',
        'sources.company_id:bigint:NOT NULL',
        'sources.cpn_id:bigint:NOT NULL',
        'sources.created_at:timestamp with time zone:NOT NULL',
        'sources.name:text:NULL',
        'sources.token_env:text:NOT NULL',
        'sources.updated_at:timestamp with time zone:NOT NULL',
        'sources.verified_at:timestamp with time zone:NULL',
        'stock_consumption_details.api_fetched_at:timestamp with time zone:NOT NULL',
        'stock_consumption_details.bsale_id:bigint:NOT NULL',
        'stock_consumption_details.company_id:bigint:NOT NULL',
        'stock_consumption_details.consumption_id:bigint:NOT NULL',
        'stock_consumption_details.first_seen_at:timestamp with time zone:NOT NULL',
        'stock_consumption_details.last_changed_at:timestamp with time zone:NOT NULL',
        'stock_consumption_details.last_seen_at:timestamp with time zone:NOT NULL',
        'stock_consumption_details.last_source:text:NOT NULL',
        'stock_consumption_details.payload:jsonb:NOT NULL',
        'stock_consumption_details.payload_hash:text:NOT NULL',
        'stock_consumption_details.quantity:numeric:NULL',
        'stock_consumption_details.sync_run_id:bigint:NULL',
        'stock_consumption_details.variant_id:bigint:NULL',
        'stock_consumptions.api_fetched_at:timestamp with time zone:NOT NULL',
        'stock_consumptions.bsale_id:bigint:NOT NULL',
        'stock_consumptions.company_id:bigint:NOT NULL',
        'stock_consumptions.consumption_date:date:NULL',
        'stock_consumptions.first_seen_at:timestamp with time zone:NOT NULL',
        'stock_consumptions.last_changed_at:timestamp with time zone:NOT NULL',
        'stock_consumptions.last_seen_at:timestamp with time zone:NOT NULL',
        'stock_consumptions.last_source:text:NOT NULL',
        'stock_consumptions.missing_since:timestamp with time zone:NULL',
        'stock_consumptions.office_id:bigint:NULL',
        'stock_consumptions.payload:jsonb:NOT NULL',
        'stock_consumptions.payload_hash:text:NOT NULL',
        'stock_consumptions.sync_run_id:bigint:NULL',
        'stock_reception_details.api_fetched_at:timestamp with time zone:NOT NULL',
        'stock_reception_details.bsale_id:bigint:NOT NULL',
        'stock_reception_details.company_id:bigint:NOT NULL',
        'stock_reception_details.cost:numeric:NULL',
        'stock_reception_details.first_seen_at:timestamp with time zone:NOT NULL',
        'stock_reception_details.last_changed_at:timestamp with time zone:NOT NULL',
        'stock_reception_details.last_seen_at:timestamp with time zone:NOT NULL',
        'stock_reception_details.last_source:text:NOT NULL',
        'stock_reception_details.payload:jsonb:NOT NULL',
        'stock_reception_details.payload_hash:text:NOT NULL',
        'stock_reception_details.quantity:numeric:NULL',
        'stock_reception_details.reception_id:bigint:NOT NULL',
        'stock_reception_details.sync_run_id:bigint:NULL',
        'stock_reception_details.variant_id:bigint:NULL',
        'stock_receptions.admission_date:date:NULL',
        'stock_receptions.api_fetched_at:timestamp with time zone:NOT NULL',
        'stock_receptions.bsale_id:bigint:NOT NULL',
        'stock_receptions.company_id:bigint:NOT NULL',
        'stock_receptions.document_number:text:NULL',
        'stock_receptions.first_seen_at:timestamp with time zone:NOT NULL',
        'stock_receptions.last_changed_at:timestamp with time zone:NOT NULL',
        'stock_receptions.last_seen_at:timestamp with time zone:NOT NULL',
        'stock_receptions.last_source:text:NOT NULL',
        'stock_receptions.missing_since:timestamp with time zone:NULL',
        'stock_receptions.office_id:bigint:NULL',
        'stock_receptions.payload:jsonb:NOT NULL',
        'stock_receptions.payload_hash:text:NOT NULL',
        'stock_receptions.sync_run_id:bigint:NULL',
        'stocks.api_fetched_at:timestamp with time zone:NOT NULL',
        'stocks.bsale_stock_id:bigint:NULL',
        'stocks.company_id:bigint:NOT NULL',
        'stocks.first_seen_at:timestamp with time zone:NOT NULL',
        'stocks.last_changed_at:timestamp with time zone:NOT NULL',
        'stocks.last_seen_at:timestamp with time zone:NOT NULL',
        'stocks.last_source:text:NOT NULL',
        'stocks.office_id:bigint:NOT NULL',
        'stocks.payload:jsonb:NOT NULL',
        'stocks.payload_hash:text:NOT NULL',
        'stocks.quantity:numeric:NULL',
        'stocks.quantity_available:numeric:NULL',
        'stocks.quantity_reserved:numeric:NULL',
        'stocks.sync_run_id:bigint:NULL',
        'stocks.variant_id:bigint:NOT NULL',
        'sync_cursors.company_id:bigint:NOT NULL',
        'sync_cursors.cursor_name:text:NOT NULL',
        'sync_cursors.cursor_value:jsonb:NOT NULL',
        'sync_cursors.cycle_started_at:timestamp with time zone:NULL',
        'sync_cursors.resource:text:NOT NULL',
        'sync_cursors.scope:text:NOT NULL',
        'sync_cursors.sync_run_id:bigint:NULL',
        'sync_cursors.updated_at:timestamp with time zone:NOT NULL',
        'sync_entity_runs.api_count:integer:NULL',
        'sync_entity_runs.company_id:bigint:NOT NULL',
        'sync_entity_runs.duration_ms:integer:NULL',
        'sync_entity_runs.error:text:NULL',
        'sync_entity_runs.finished_at:timestamp with time zone:NULL',
        'sync_entity_runs.fuse:jsonb:NULL',
        'sync_entity_runs.http_429:integer:NOT NULL',
        'sync_entity_runs.http_5xx:integer:NOT NULL',
        'sync_entity_runs.id:bigint:NOT NULL',
        'sync_entity_runs.requests:integer:NOT NULL',
        'sync_entity_runs.resource:text:NOT NULL',
        'sync_entity_runs.rows_deleted:integer:NOT NULL',
        'sync_entity_runs.rows_inserted:integer:NOT NULL',
        'sync_entity_runs.rows_missing:integer:NOT NULL',
        'sync_entity_runs.rows_received:integer:NOT NULL',
        'sync_entity_runs.rows_skipped_newer:integer:NOT NULL',
        'sync_entity_runs.rows_unchanged:integer:NOT NULL',
        'sync_entity_runs.rows_updated:integer:NOT NULL',
        'sync_entity_runs.scope:text:NOT NULL',
        'sync_entity_runs.snapshot_started_at:timestamp with time zone:NULL',
        'sync_entity_runs.started_at:timestamp with time zone:NOT NULL',
        'sync_entity_runs.status:text:NOT NULL',
        'sync_entity_runs.sync_run_id:bigint:NOT NULL',
        'sync_runs.error:text:NULL',
        'sync_runs.finished_at:timestamp with time zone:NULL',
        'sync_runs.host:text:NULL',
        'sync_runs.id:bigint:NOT NULL',
        'sync_runs.mode:text:NOT NULL',
        'sync_runs.started_at:timestamp with time zone:NOT NULL',
        'sync_runs.status:text:NOT NULL',
        'sync_runs.summary:jsonb:NULL',
        'sync_runs.trigger:text:NOT NULL',
        'sync_state.company_id:bigint:NOT NULL',
        'sync_state.duration_ms:integer:NULL',
        'sync_state.last_attempt_at:timestamp with time zone:NULL',
        'sync_state.last_error:text:NULL',
        'sync_state.last_error_at:timestamp with time zone:NULL',
        'sync_state.last_full_reconcile_at:timestamp with time zone:NULL',
        'sync_state.last_incremental_at:timestamp with time zone:NULL',
        'sync_state.last_success_at:timestamp with time zone:NULL',
        'sync_state.last_sync_run_id:bigint:NULL',
        'sync_state.last_webhook_at:timestamp with time zone:NULL',
        'sync_state.resource:text:NOT NULL',
        'sync_state.rows_received:integer:NULL',
        'sync_state.scope:text:NOT NULL',
        'sync_state.status:text:NULL',
        'sync_state.updated_at:timestamp with time zone:NOT NULL',
        'taxes.api_fetched_at:timestamp with time zone:NOT NULL',
        'taxes.bsale_id:bigint:NOT NULL',
        'taxes.code:text:NULL',
        'taxes.company_id:bigint:NOT NULL',
        'taxes.first_seen_at:timestamp with time zone:NOT NULL',
        'taxes.last_changed_at:timestamp with time zone:NOT NULL',
        'taxes.last_seen_at:timestamp with time zone:NOT NULL',
        'taxes.last_source:text:NOT NULL',
        'taxes.missing_since:timestamp with time zone:NULL',
        'taxes.name:text:NULL',
        'taxes.payload:jsonb:NOT NULL',
        'taxes.payload_hash:text:NOT NULL',
        'taxes.percentage:numeric:NULL',
        'taxes.state:smallint:NULL',
        'taxes.sync_run_id:bigint:NULL',
        'variant_costs.api_fetched_at:timestamp with time zone:NOT NULL',
        'variant_costs.average_cost:numeric:NULL',
        'variant_costs.company_id:bigint:NOT NULL',
        'variant_costs.first_seen_at:timestamp with time zone:NOT NULL',
        'variant_costs.history_complete:boolean:NOT NULL',
        'variant_costs.history_count:integer:NULL',
        'variant_costs.last_admission_date:date:NULL',
        'variant_costs.last_changed_at:timestamp with time zone:NOT NULL',
        'variant_costs.last_seen_at:timestamp with time zone:NOT NULL',
        'variant_costs.last_source:text:NOT NULL',
        'variant_costs.payload:jsonb:NOT NULL',
        'variant_costs.payload_hash:text:NOT NULL',
        'variant_costs.sync_run_id:bigint:NULL',
        'variant_costs.total_cost:numeric:NULL',
        'variant_costs.variant_id:bigint:NOT NULL',
        'variant_prices.api_fetched_at:timestamp with time zone:NOT NULL',
        'variant_prices.bsale_detail_id:bigint:NULL',
        'variant_prices.company_id:bigint:NOT NULL',
        'variant_prices.first_seen_at:timestamp with time zone:NOT NULL',
        'variant_prices.last_changed_at:timestamp with time zone:NOT NULL',
        'variant_prices.last_seen_at:timestamp with time zone:NOT NULL',
        'variant_prices.last_source:text:NOT NULL',
        'variant_prices.missing_since:timestamp with time zone:NULL',
        'variant_prices.payload:jsonb:NOT NULL',
        'variant_prices.payload_hash:text:NOT NULL',
        'variant_prices.price_list_id:bigint:NOT NULL',
        'variant_prices.sync_run_id:bigint:NULL',
        'variant_prices.variant_id:bigint:NOT NULL',
        'variant_prices.variant_value:numeric:NULL',
        'variant_prices.variant_value_with_taxes:numeric:NULL',
        'variants.api_fetched_at:timestamp with time zone:NOT NULL',
        'variants.bar_code:text:NULL',
        'variants.bsale_id:bigint:NOT NULL',
        'variants.code:text:NULL',
        'variants.company_id:bigint:NOT NULL',
        'variants.description:text:NULL',
        'variants.first_seen_at:timestamp with time zone:NOT NULL',
        'variants.last_changed_at:timestamp with time zone:NOT NULL',
        'variants.last_seen_at:timestamp with time zone:NOT NULL',
        'variants.last_source:text:NOT NULL',
        'variants.missing_since:timestamp with time zone:NULL',
        'variants.payload:jsonb:NOT NULL',
        'variants.payload_hash:text:NOT NULL',
        'variants.product_id:bigint:NULL',
        'variants.state:smallint:NULL',
        'variants.sync_run_id:bigint:NULL',
        'variants.unlimited_stock:smallint:NULL',
        'webhook_events.action:text:NULL',
        'webhook_events.attempts:integer:NOT NULL',
        'webhook_events.coalesced_into_id:bigint:NULL',
        'webhook_events.company_id:bigint:NULL',
        'webhook_events.cpn_id:bigint:NULL',
        'webhook_events.dedupe_key:text:NULL',
        'webhook_events.id:bigint:NOT NULL',
        'webhook_events.last_error:text:NULL',
        'webhook_events.locked_at:timestamp with time zone:NULL',
        'webhook_events.locked_by:text:NULL',
        'webhook_events.next_attempt_at:timestamp with time zone:NOT NULL',
        'webhook_events.office_id:bigint:NULL',
        'webhook_events.payload:jsonb:NOT NULL',
        'webhook_events.price_list_id:bigint:NULL',
        'webhook_events.processed_at:timestamp with time zone:NULL',
        'webhook_events.received_at:timestamp with time zone:NOT NULL',
        'webhook_events.refresh_key:text:NULL',
        'webhook_events.resource:text:NULL',
        'webhook_events.resource_id:bigint:NULL',
        'webhook_events.sent_at:bigint:NULL',
        'webhook_events.status:text:NOT NULL',
        'webhook_events.topic:text:NULL',
        'webhook_events.validation_error:text:NULL',
        'webhook_resource_responses.body:jsonb:NULL',
        'webhook_resource_responses.body_hash:text:NULL',
        'webhook_resource_responses.body_text:text:NULL',
        'webhook_resource_responses.company_id:bigint:NOT NULL',
        'webhook_resource_responses.duration_ms:integer:NULL',
        'webhook_resource_responses.envelope:text:NOT NULL',
        'webhook_resource_responses.fetched_at:timestamp with time zone:NOT NULL',
        'webhook_resource_responses.http_status:integer:NULL',
        'webhook_resource_responses.id:bigint:NOT NULL',
        'webhook_resource_responses.requested_path:text:NOT NULL',
        'webhook_resource_responses.response_code:integer:NULL',
        'webhook_resource_responses.webhook_event_id:bigint:NOT NULL'
    ];
    expected_constraints text[] := ARRAY[
        'clients.ck_raw_clients_last_source:c',
        'clients.fk_raw_clients_company:f',
        'clients.pk_raw_clients:p',
        'document_change_log.ck_raw_document_change_log_change_kind:c',
        'document_change_log.ck_raw_document_change_log_detected_by:c',
        'document_change_log.fk_raw_document_change_log_company:f',
        'document_change_log.pk_raw_document_change_log:p',
        'document_details.ck_raw_document_details_last_source:c',
        'document_details.fk_raw_document_details_company:f',
        'document_details.pk_raw_document_details:p',
        'document_references.ck_raw_document_references_last_source:c',
        'document_references.fk_raw_document_references_company:f',
        'document_references.pk_raw_document_references:p',
        'document_sellers.ck_raw_document_sellers_last_source:c',
        'document_sellers.fk_raw_document_sellers_company:f',
        'document_sellers.pk_raw_document_sellers:p',
        'document_types.ck_raw_document_types_last_source:c',
        'document_types.fk_raw_document_types_company:f',
        'document_types.pk_raw_document_types:p',
        'documents.ck_raw_documents_last_source:c',
        'documents.fk_raw_documents_company:f',
        'documents.pk_raw_documents:p',
        'offices.ck_raw_offices_last_source:c',
        'offices.fk_raw_offices_company:f',
        'offices.pk_raw_offices:p',
        'price_lists.ck_raw_price_lists_last_source:c',
        'price_lists.fk_raw_price_lists_company:f',
        'price_lists.pk_raw_price_lists:p',
        'product_taxes.ck_raw_product_taxes_last_source:c',
        'product_taxes.fk_raw_product_taxes_company:f',
        'product_taxes.pk_raw_product_taxes:p',
        'product_types.ck_raw_product_types_last_source:c',
        'product_types.fk_raw_product_types_company:f',
        'product_types.pk_raw_product_types:p',
        'products.ck_raw_products_last_source:c',
        'products.fk_raw_products_company:f',
        'products.pk_raw_products:p',
        'sources.ck_raw_sources_token_env:c',
        'sources.fk_raw_sources_company:f',
        'sources.pk_raw_sources:p',
        'sources.uq_raw_sources_cpn_id:u',
        'stock_consumption_details.ck_raw_stock_consumption_details_last_source:c',
        'stock_consumption_details.fk_raw_stock_consumption_details_company:f',
        'stock_consumption_details.pk_raw_stock_consumption_details:p',
        'stock_consumptions.ck_raw_stock_consumptions_last_source:c',
        'stock_consumptions.fk_raw_stock_consumptions_company:f',
        'stock_consumptions.pk_raw_stock_consumptions:p',
        'stock_reception_details.ck_raw_stock_reception_details_last_source:c',
        'stock_reception_details.fk_raw_stock_reception_details_company:f',
        'stock_reception_details.pk_raw_stock_reception_details:p',
        'stock_receptions.ck_raw_stock_receptions_last_source:c',
        'stock_receptions.fk_raw_stock_receptions_company:f',
        'stock_receptions.pk_raw_stock_receptions:p',
        'stocks.ck_raw_stocks_last_source:c',
        'stocks.fk_raw_stocks_company:f',
        'stocks.pk_raw_stocks:p',
        'sync_cursors.fk_raw_sync_cursors_company:f',
        'sync_cursors.pk_raw_sync_cursors:p',
        'sync_entity_runs.ck_raw_sync_entity_runs_status:c',
        'sync_entity_runs.fk_raw_sync_entity_runs_company:f',
        'sync_entity_runs.fk_raw_sync_entity_runs_run:f',
        'sync_entity_runs.pk_raw_sync_entity_runs:p',
        'sync_runs.ck_raw_sync_runs_mode:c',
        'sync_runs.ck_raw_sync_runs_status:c',
        'sync_runs.pk_raw_sync_runs:p',
        'sync_state.ck_raw_sync_state_status:c',
        'sync_state.fk_raw_sync_state_company:f',
        'sync_state.pk_raw_sync_state:p',
        'taxes.ck_raw_taxes_last_source:c',
        'taxes.fk_raw_taxes_company:f',
        'taxes.pk_raw_taxes:p',
        'variant_costs.ck_raw_variant_costs_last_source:c',
        'variant_costs.fk_raw_variant_costs_company:f',
        'variant_costs.pk_raw_variant_costs:p',
        'variant_prices.ck_raw_variant_prices_last_source:c',
        'variant_prices.fk_raw_variant_prices_company:f',
        'variant_prices.pk_raw_variant_prices:p',
        'variants.ck_raw_variants_last_source:c',
        'variants.fk_raw_variants_company:f',
        'variants.pk_raw_variants:p',
        'webhook_events.ck_raw_webhook_events_status:c',
        'webhook_events.fk_raw_webhook_events_coalesced:f',
        'webhook_events.fk_raw_webhook_events_company:f',
        'webhook_events.pk_raw_webhook_events:p',
        'webhook_resource_responses.ck_raw_webhook_resource_responses_envelope:c',
        'webhook_resource_responses.fk_raw_webhook_resource_responses_company:f',
        'webhook_resource_responses.fk_raw_webhook_resource_responses_event:f',
        'webhook_resource_responses.pk_raw_webhook_resource_responses:p'
    ];
    expected_pks text[] := ARRAY[
        'clients:company_id,bsale_id',
        'document_change_log:id',
        'document_details:company_id,document_id,bsale_id',
        'document_references:company_id,document_id,bsale_id',
        'document_sellers:company_id,document_id,user_id',
        'document_types:company_id,bsale_id',
        'documents:company_id,bsale_id',
        'offices:company_id,bsale_id',
        'price_lists:company_id,bsale_id',
        'product_taxes:company_id,product_id',
        'product_types:company_id,bsale_id',
        'products:company_id,bsale_id',
        'sources:company_id',
        'stock_consumption_details:company_id,consumption_id,bsale_id',
        'stock_consumptions:company_id,bsale_id',
        'stock_reception_details:company_id,reception_id,bsale_id',
        'stock_receptions:company_id,bsale_id',
        'stocks:company_id,variant_id,office_id',
        'sync_cursors:company_id,resource,scope,cursor_name',
        'sync_entity_runs:id',
        'sync_runs:id',
        'sync_state:company_id,resource,scope',
        'taxes:company_id,bsale_id',
        'variant_costs:company_id,variant_id',
        'variant_prices:company_id,price_list_id,variant_id',
        'variants:company_id,bsale_id',
        'webhook_events:id',
        'webhook_resource_responses:id'
    ];
    expected_fks text[] := ARRAY[
        'clients.fk_raw_clients_company:company_id->bsale.companies(company_id)',
        'document_change_log.fk_raw_document_change_log_company:company_id->bsale.companies(company_id)',
        'document_details.fk_raw_document_details_company:company_id->bsale.companies(company_id)',
        'document_references.fk_raw_document_references_company:company_id->bsale.companies(company_id)',
        'document_sellers.fk_raw_document_sellers_company:company_id->bsale.companies(company_id)',
        'document_types.fk_raw_document_types_company:company_id->bsale.companies(company_id)',
        'documents.fk_raw_documents_company:company_id->bsale.companies(company_id)',
        'offices.fk_raw_offices_company:company_id->bsale.companies(company_id)',
        'price_lists.fk_raw_price_lists_company:company_id->bsale.companies(company_id)',
        'product_taxes.fk_raw_product_taxes_company:company_id->bsale.companies(company_id)',
        'product_types.fk_raw_product_types_company:company_id->bsale.companies(company_id)',
        'products.fk_raw_products_company:company_id->bsale.companies(company_id)',
        'sources.fk_raw_sources_company:company_id->bsale.companies(company_id)',
        'stock_consumption_details.fk_raw_stock_consumption_details_company:company_id->bsale.companies(company_id)',
        'stock_consumptions.fk_raw_stock_consumptions_company:company_id->bsale.companies(company_id)',
        'stock_reception_details.fk_raw_stock_reception_details_company:company_id->bsale.companies(company_id)',
        'stock_receptions.fk_raw_stock_receptions_company:company_id->bsale.companies(company_id)',
        'stocks.fk_raw_stocks_company:company_id->bsale.companies(company_id)',
        'sync_cursors.fk_raw_sync_cursors_company:company_id->bsale.companies(company_id)',
        'sync_entity_runs.fk_raw_sync_entity_runs_company:company_id->bsale.companies(company_id)',
        'sync_entity_runs.fk_raw_sync_entity_runs_run:sync_run_id->bsale_raw.sync_runs(id)',
        'sync_state.fk_raw_sync_state_company:company_id->bsale.companies(company_id)',
        'taxes.fk_raw_taxes_company:company_id->bsale.companies(company_id)',
        'variant_costs.fk_raw_variant_costs_company:company_id->bsale.companies(company_id)',
        'variant_prices.fk_raw_variant_prices_company:company_id->bsale.companies(company_id)',
        'variants.fk_raw_variants_company:company_id->bsale.companies(company_id)',
        'webhook_events.fk_raw_webhook_events_coalesced:coalesced_into_id->bsale_raw.webhook_events(id)',
        'webhook_events.fk_raw_webhook_events_company:company_id->bsale.companies(company_id)',
        'webhook_resource_responses.fk_raw_webhook_resource_responses_company:company_id->bsale.companies(company_id)',
        'webhook_resource_responses.fk_raw_webhook_resource_responses_event:webhook_event_id->bsale_raw.webhook_events(id)'
    ];
    expected_indexes text[] := ARRAY[
        'clients.ix_raw_clients_code:i',
        'clients.ix_raw_clients_fetched:i',
        'clients.pk_raw_clients:u',
        'document_change_log.ix_raw_document_change_log_document:i',
        'document_change_log.ix_raw_document_change_log_pending_stock:i',
        'document_change_log.pk_raw_document_change_log:u',
        'document_details.ix_raw_document_details_bsale_id:i',
        'document_details.ix_raw_document_details_variant:i',
        'document_details.pk_raw_document_details:u',
        'document_references.ix_raw_document_references_bsale_id:i',
        'document_references.pk_raw_document_references:u',
        'document_sellers.ix_raw_document_sellers_user:i',
        'document_sellers.pk_raw_document_sellers:u',
        'document_types.ix_raw_document_types_code_sii:i',
        'document_types.pk_raw_document_types:u',
        'documents.ix_raw_documents_client:i',
        'documents.ix_raw_documents_generation:i',
        'documents.ix_raw_documents_number:i',
        'documents.ix_raw_documents_office_emission:i',
        'documents.ix_raw_documents_type_emission:i',
        'documents.ix_raw_documents_type_state:i',
        'documents.ix_raw_documents_watch:i',
        'documents.pk_raw_documents:u',
        'offices.pk_raw_offices:u',
        'price_lists.pk_raw_price_lists:u',
        'product_taxes.ix_raw_product_taxes_fetched:i',
        'product_taxes.pk_raw_product_taxes:u',
        'product_types.pk_raw_product_types:u',
        'products.ix_raw_products_fetched:i',
        'products.ix_raw_products_type:i',
        'products.pk_raw_products:u',
        'sources.pk_raw_sources:u',
        'sources.uq_raw_sources_cpn_id:u',
        'stock_consumption_details.ix_raw_stock_consumption_details_bsale_id:i',
        'stock_consumption_details.ix_raw_stock_consumption_details_variant:i',
        'stock_consumption_details.pk_raw_stock_consumption_details:u',
        'stock_consumptions.ix_raw_stock_consumptions_office_date:i',
        'stock_consumptions.pk_raw_stock_consumptions:u',
        'stock_reception_details.ix_raw_stock_reception_details_bsale_id:i',
        'stock_reception_details.ix_raw_stock_reception_details_variant:i',
        'stock_reception_details.pk_raw_stock_reception_details:u',
        'stock_receptions.ix_raw_stock_receptions_office_date:i',
        'stock_receptions.pk_raw_stock_receptions:u',
        'stocks.ix_raw_stocks_bsale_stock_id:i',
        'stocks.ix_raw_stocks_office_fetched:i',
        'stocks.pk_raw_stocks:u',
        'sync_cursors.pk_raw_sync_cursors:u',
        'sync_entity_runs.ix_raw_sync_entity_runs_lookup:i',
        'sync_entity_runs.ix_raw_sync_entity_runs_run:i',
        'sync_entity_runs.pk_raw_sync_entity_runs:u',
        'sync_runs.ix_raw_sync_runs_mode_started:i',
        'sync_runs.ix_raw_sync_runs_running:i',
        'sync_runs.pk_raw_sync_runs:u',
        'sync_state.ix_raw_sync_state_resource:i',
        'sync_state.pk_raw_sync_state:u',
        'taxes.pk_raw_taxes:u',
        'variant_costs.ix_raw_variant_costs_fetched:i',
        'variant_costs.pk_raw_variant_costs:u',
        'variant_prices.ix_raw_variant_prices_bsale_detail_id:i',
        'variant_prices.ix_raw_variant_prices_list_fetched:i',
        'variant_prices.ix_raw_variant_prices_variant:i',
        'variant_prices.pk_raw_variant_prices:u',
        'variants.ix_raw_variants_bar_code:i',
        'variants.ix_raw_variants_code:i',
        'variants.ix_raw_variants_fetched:i',
        'variants.ix_raw_variants_product:i',
        'variants.pk_raw_variants:u',
        'webhook_events.ix_raw_webhook_events_company_received:i',
        'webhook_events.ix_raw_webhook_events_dedupe:i',
        'webhook_events.ix_raw_webhook_events_processing_lock:i',
        'webhook_events.ix_raw_webhook_events_queue:i',
        'webhook_events.pk_raw_webhook_events:u',
        'webhook_events.uq_raw_webhook_events_processing_refresh:u',
        'webhook_events.uq_raw_webhook_events_queued_refresh:u',
        'webhook_resource_responses.ix_raw_webhook_resource_responses_event:i',
        'webhook_resource_responses.ix_raw_webhook_resource_responses_fetched:i',
        'webhook_resource_responses.pk_raw_webhook_resource_responses:u'
    ];
    -- END GENERATED EXPECTED
    act_tables text[];
    act_columns text[];
    act_constraints text[];
    act_pks text[];
    act_fks text[];
    act_indexes text[];
    rec record;
    missing text[];
    extra text[];
    problems text[] := '{}';
BEGIN
    IF to_regnamespace('bsale_raw') IS NULL THEN
        RAISE EXCEPTION 'bsale_raw: el schema no existe';
    END IF;

    SELECT coalesce(array_agg(c.relname::text), '{}') INTO act_tables
    FROM pg_class c
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'bsale_raw' AND c.relkind IN ('r', 'p');

    SELECT coalesce(array_agg(format('%s.%s:%s:%s', c.relname, a.attname,
                                     format_type(a.atttypid, a.atttypmod),
                                     CASE WHEN a.attnotnull THEN 'NOT NULL' ELSE 'NULL' END)), '{}')
    INTO act_columns
    FROM pg_attribute a
    JOIN pg_class c ON c.oid = a.attrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'bsale_raw' AND c.relkind IN ('r', 'p') AND a.attnum > 0 AND NOT a.attisdropped;

    SELECT coalesce(array_agg(format('%s.%s:%s', c.relname, k.conname, k.contype)), '{}')
    INTO act_constraints
    FROM pg_constraint k
    JOIN pg_class c ON c.oid = k.conrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'bsale_raw' AND k.contype IN ('p', 'f', 'u', 'c');

    SELECT coalesce(array_agg(format('%s:%s', c.relname,
        (SELECT string_agg(a.attname::text, ',' ORDER BY u.ord)
         FROM unnest(k.conkey) WITH ORDINALITY AS u(attnum, ord)
         JOIN pg_attribute a ON a.attrelid = k.conrelid AND a.attnum = u.attnum))), '{}')
    INTO act_pks
    FROM pg_constraint k
    JOIN pg_class c ON c.oid = k.conrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    WHERE n.nspname = 'bsale_raw' AND k.contype = 'p';

    SELECT coalesce(array_agg(format('%s.%s:%s->%s.%s(%s)', c.relname, k.conname,
        (SELECT string_agg(a.attname::text, ',' ORDER BY u.ord)
         FROM unnest(k.conkey) WITH ORDINALITY AS u(attnum, ord)
         JOIN pg_attribute a ON a.attrelid = k.conrelid AND a.attnum = u.attnum),
        tn.nspname, tc.relname,
        (SELECT string_agg(a.attname::text, ',' ORDER BY u.ord)
         FROM unnest(k.confkey) WITH ORDINALITY AS u(attnum, ord)
         JOIN pg_attribute a ON a.attrelid = k.confrelid AND a.attnum = u.attnum))), '{}')
    INTO act_fks
    FROM pg_constraint k
    JOIN pg_class c ON c.oid = k.conrelid
    JOIN pg_namespace n ON n.oid = c.relnamespace
    JOIN pg_class tc ON tc.oid = k.confrelid
    JOIN pg_namespace tn ON tn.oid = tc.relnamespace
    WHERE n.nspname = 'bsale_raw' AND k.contype = 'f';

    SELECT coalesce(array_agg(format('%s.%s:%s', t.relname, i.relname,
                                     CASE WHEN x.indisunique THEN 'u' ELSE 'i' END)), '{}')
    INTO act_indexes
    FROM pg_index x
    JOIN pg_class i ON i.oid = x.indexrelid
    JOIN pg_class t ON t.oid = x.indrelid
    JOIN pg_namespace n ON n.oid = t.relnamespace
    WHERE n.nspname = 'bsale_raw';

    FOR rec IN
        SELECT * FROM (VALUES
            ('tablas', expected_tables, act_tables),
            ('columnas', expected_columns, act_columns),
            ('constraints', expected_constraints, act_constraints),
            ('primary keys', expected_pks, act_pks),
            ('foreign keys', expected_fks, act_fks),
            ('indices', expected_indexes, act_indexes)
        ) AS v(label, expected, actual)
    LOOP
        SELECT coalesce(array_agg(e ORDER BY e), '{}') INTO missing
        FROM unnest(rec.expected) AS e WHERE e <> ALL (rec.actual);
        SELECT coalesce(array_agg(a ORDER BY a), '{}') INTO extra
        FROM unnest(rec.actual) AS a WHERE a <> ALL (rec.expected);
        IF cardinality(missing) > 0 THEN
            problems := problems || format('%s faltantes: %s', rec.label, array_to_string(missing, ', '));
        END IF;
        IF cardinality(extra) > 0 THEN
            problems := problems || format('%s no esperados: %s', rec.label, array_to_string(extra, ', '));
        END IF;
    END LOOP;

    IF cardinality(problems) > 0 THEN
        RAISE EXCEPTION E'bsale_raw drift detectado:\n%', array_to_string(problems, E'\n');
    END IF;
    RAISE NOTICE 'bsale_raw OK: % tablas, % columnas, % índices',
        cardinality(expected_tables), cardinality(expected_columns), cardinality(expected_indexes);
END
$verify$;
