-- Propuesta (NO aplicar en este fix): columna source_document_id en documents.
-- Objetivo: materializar el id Bsale vigente cuando difiere de document_id (PK local
-- por ON CONFLICT folio), y indexar lookups de sync de hijos / diagnóstico.
--
-- Uso previsto tras el fix de runtime (raw_document["id"] / raw_data->>'id'):
--   1. Backfill: UPDATE documents SET source_document_id = (raw_data->>'id')::bigint
--      WHERE raw_data ? 'id';
--   2. Sync: al upsert, setear source_document_id = Bsale id del payload.
--   3. Hijos: GET /documents/{COALESCE(source_document_id, document_id)}/...
--
-- Este archivo es documentación + DDL candidato; apply_distribuidora_schema lo
-- aplicará solo cuando se apruebe explícitamente el rollout.

-- +goose Up
-- ALTER TABLE distribuidora.documents
--     ADD COLUMN IF NOT EXISTS source_document_id BIGINT;
--
-- COMMENT ON COLUMN distribuidora.documents.source_document_id IS
--     'Id vigente del documento en Bsale (puede diferir de document_id tras reemisión).';
--
-- CREATE INDEX IF NOT EXISTS idx_documents_source_document_id
--     ON distribuidora.documents (source_document_id)
--     WHERE source_document_id IS NOT NULL;
--
-- UPDATE distribuidora.documents
-- SET source_document_id = (raw_data->>'id')::bigint
-- WHERE source_document_id IS NULL
--   AND raw_data ? 'id'
--   AND (raw_data->>'id') ~ '^[0-9]+$';

-- +goose Down
-- ALTER TABLE distribuidora.documents DROP COLUMN IF EXISTS source_document_id;
